name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  local_test_job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Print Java version
        run: javac -version
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Access GOOGLE_MAPS_API_KEY
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: echo GOOGLE_MAPS_API_KEY=\"$GOOGLE_MAPS_API_KEY\" > ./local.properties      
      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

#  android_test_job:
#    runs-on: macos-11
#    strategy:
#      matrix:
#        api-level: [ 33, 28 ]
#    steps:
 #     - name: checkout
#        uses: actions/checkout@v3

 #     - name: Gradle cache
 #       uses: gradle/gradle-build-action@v2

#      - name: Change wrapper permissions
#        run: chmod +x ./gradlew

#      - name: AVD cache
#        uses: actions/cache@v3
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ matrix.api-level }}

#      - name: create AVD and generate snapshot for caching
#        if: steps.avd-cache.outputs.cache-hit != 'true'
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          force-avd-creation: false
#          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: false
#          script: echo "Generated AVD snapshot for caching."
#          emulator-build: 7425822

#      - name: run android tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          force-avd-creation: false
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: ./gradlew connectedCheck
#    name: Android Tests
#    runs-on: macos-latest
#    continue-on-error: true
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Change wrapper permissions
#        run: chmod +x ./gradlew
#      - name: Restore Cache
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Android Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
#
#      - name: Upload Android Test Reports
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: android-test-reports
#          path: '**/build/reports/androidTests/'
